### ISSUE TITLE
Change extension to .mp3

### ISSUE THREAD

**Issue by magadan** [eibrahim95/discord-voice-messages#1]
Hello, thank you for the extension ! Its great.

Its possible to change the extension to .mp3 instead .wav ? Im trying to find this line of code..

**Comment by eibrahim995** [comment]
Hello, 
I've tried to encode to mp3, but I've got into problems related to the need for the encoding to be done in a [ web worker](https://developer.mozilla.org/en-US/docs/Web/API/Worker), which discord prevent us from doing.

I might have another look at it later, but if you wanna try, you could change "WAV" in this [line](https://github.com/eibrahim995/discord-voice-messages/blob/main/src/App.js#L60) to one of [320, 256, 192, 128, 96, 64, 56, 48, 40, 32], and maybe change the extension and the mime-type in this [line](https://github.com/eibrahim995/discord-voice-messages/blob/main/src/App.js#L18).

For more information about the encoding part, this is the package I'm using: [audio-encoder](https://www.npmjs.com/package/audio-encoder).

Let me know if I can help you with something else.

**Comment by magadan** [comment]
Thanks ebrahim, i just change the extension to .mp3 in one line only, its enough to make another project [WhatsAppToDiscord](https://github.com/FKLC/WhatsAppToDiscord) accepts the voice message. Its working. 

Do you know if is possible to inject into discord client ? Or with another good opensource fork ?

thank you.

**Comment by eibrahim995** [comment]
No, sorry, this was designed to work only with the web app on google chrome.
Closing the issue, seeing that you solved your issue.
