### ISSUE TITLE
API Endpoint

### ISSUE THREAD

**Issue by vgthecoder** [eibrahim95/discord-voice-messages#4]
What API endpoint is this using to send the voice message?

**Comment by eibrahim95** [comment]
This is not using any endpoints, it is just using the dom in the page to attach the audio and send it, as if you did it yourself.

**Comment by vgthecoder** [comment]
Okay, what DOM element is it? Can I have the tagname, class, or id?

**Comment by eibrahim95** [comment]
@vgthecoder see https://github.com/eibrahim95/discord-voice-messages/blob/main/src/index.js#L7C3-L7C126
It is this line : `const discordChatButtonsContainer = document.getElementsByClassName("expression-picker-chat-input-button")[0].parentElement`

The dom element is injected by this extension, it is injected in the parent of with the element with the  classname `expression-picker-chat-input-button`

**Comment by vgthecoder** [comment]
Oh I get it now. This isn't actually sending a voice message, like you can on mobile.
